version: "3"

services:
  mongo:
    image: mongo:3.6.2-jessie
    container_name: pgazienda-mongo
    ports:
      - "50000:27017"
    volumes:
      - mongo-data:/data/db
  pgazienda:
    build: 
      context: .
    container_name: pgazienda
    ports:
      - "8010:8080"
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    env_file: ./docker-configs/app.env
volumes:
  mongo-data: