version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: pgazienda-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: pgazienda
      MONGO_INITDB_ROOT_PASSWORD: pgazienda   
    ports:
      - "50000:27017"
    volumes:
      - mongo-data:/data/db
  pgazienda:
    build: 
      context: .
    container_name: pgazienda
    ports:
      - "8010:8080"
      - "7878:7878"
    depends_on:
      - mongo
    links:
      - mongo:mongodb
    env_file: ./docker-configs/app.env
volumes:
  mongo-data: